// Package trinetra: enroll.go holds the shared Telegram enrollment-pin state (#90).
package trinetra

import (
	"log"
	"strings"
	"sync"
	"time"

	"github.com/InfoDiveLabs/trinetra/internal/config"
)

// enrollState holds the current Telegram enrollment PIN and the brute-force bookkeeping for
// the unclaimed-bot "/start <pin>" path (#93).
type enrollState struct {
	mu  sync.Mutex
	pin string
	// failures counts consecutive wrong "/start <pin>" guesses since the last success or
	// rotation; on reaching cfg.EnrollMaxAttempts the pin cools down.
	failures int
	// cooldownUntil is the instant before which every "/start" attempt is ignored (the
	// rate-limit half of the brute-force bound).
	cooldownUntil time.Time
}

// PIN returns the active enrollment pin for cfg: if telegram is configured (token set) AND
// not yet enrolled (chat id empty), it returns the pin.
func (e *enrollState) PIN(cfg *config.Config) (pin string, enrolled bool) {
	if cfg == nil {
		return "", false
	}
	if cfg.Telegram.ChatID != "" {
		return "", true
	}
	if cfg.Telegram.Token == "" {
		return "", false
	}

	e.mu.Lock()
	defer e.mu.Unlock()
	if e.pin == "" {
		e.pin = newEnrollPIN()
	}
	return e.pin, false
}

// Reset clears the cached pin and the brute-force counters.
func (e *enrollState) Reset() {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.pin = ""
	e.failures = 0
	e.cooldownUntil = time.Time{}
}

// Attempt evaluates one inbound message text against the current enrollment PIN while the
// bot is unclaimed, updating brute-force state.
func (e *enrollState) Attempt(cfg *config.Config, text string, now time.Time) bool {
	// PIN applies the "configured AND not yet enrolled" gate and generates and caches the pin
	// on first call; an empty pin.
	if pin, _ := e.PIN(cfg); pin == "" {
		return false
	}

	// A message that is not a "/start <arg>" command is not an enrollment attempt at all:
	// ignore it without counting it.
	f := strings.Fields(text)
	if len(f) != 2 || f[0] != "/start" {
		return false
	}

	e.mu.Lock()
	defer e.mu.Unlock()
	// e.pin may have just been generated by PIN above, or rotated by a prior
	// Attempt -- re-read it under the lock and treat "" as never-matching.
	if e.pin == "" || now.Before(e.cooldownUntil) {
		return false
	}
	if f[1] == e.pin {
		e.failures = 0
		return true
	}
	e.failures++
	if e.failures >= cfg.EnrollMaxAttempts() {
		e.cooldownUntil = now.Add(time.Duration(cfg.EnrollCooldownSec()) * time.Second)
		e.pin = newEnrollPIN()
		e.failures = 0
		log.Printf("telegram: %d wrong /start attempts; enrollment PIN rotated and /start ignored for %ds. New PIN: /start %s",
			cfg.EnrollMaxAttempts(), cfg.EnrollCooldownSec(), e.pin)
	}
	return false
}
